import IStrapiData from '../../models/strapi/IStrapiData';
import StrapiMedia from '../../models/strapi/StrapiMedia';

export const strapiMediaMock: IStrapiData<StrapiMedia> = {
  id: 5,
  attributes: {
    name: 'cover.jpeg',
    alternativeText: '',
    caption: '',
    width: 2000,
    height: 1335,
    formats: {
      thumbnail: {
        name: 'thumbnail_cover.jpeg',
        hash: 'thumbnail_cover_e0ebb03d1c',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 234,
        height: 156,
        size: 6.54,
        path: null,
        url: '/uploads/thumbnail_cover_e0ebb03d1c.jpeg',
      },
      xLarge: {
        name: 'xLarge_cover.jpeg',
        hash: 'xLarge_cover_e0ebb03d1c',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 1920,
        height: 1282,
        size: 417.54,
        path: null,
        url: '/uploads/xLarge_cover_e0ebb03d1c.jpeg',
      },
      large: {
        name: 'large_cover.jpeg',
        hash: 'large_cover_e0ebb03d1c',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 1000,
        height: 668,
        size: 111.69,
        path: null,
        url: '/uploads/large_cover_e0ebb03d1c.jpeg',
      },
      medium: {
        name: 'medium_cover.jpeg',
        hash: 'medium_cover_e0ebb03d1c',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 750,
        height: 501,
        size: 62.81,
        path: null,
        url: '/uploads/medium_cover_e0ebb03d1c.jpeg',
      },
      small: {
        name: 'small_cover.jpeg',
        hash: 'small_cover_e0ebb03d1c',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 500,
        height: 334,
        size: 28.67,
        path: null,
        url: '/uploads/small_cover_e0ebb03d1c.jpeg',
      },
      xSmall: {
        name: 'xSmall_cover.jpeg',
        hash: 'xSmall_cover_e0ebb03d1c',
        ext: '.jpeg',
        mime: 'image/jpeg',
        width: 64,
        height: 43,
        size: 1.03,
        path: null,
        url: '/uploads/xSmall_cover_e0ebb03d1c.jpeg',
      },
    },
    hash: 'cover_e0ebb03d1c',
    ext: '.jpeg',
    mime: 'image/jpeg',
    size: 450.94,
    url: '/uploads/cover_e0ebb03d1c.jpeg',
    previewUrl: null,
    provider: 'local',
    provider_metadata: null,
    createdAt: '2021-08-17T20:25:31.590Z',
    updatedAt: '2021-08-17T20:25:31.601Z',
  },
};
