import IStrapiData from '@/models/strapi/IStrapiData';
import StrapiBlogPost from '@/models/strapi/StrapiBlogPost';

export const strapiBlogPostMock: IStrapiData<StrapiBlogPost> = {
  id: 1,
  attributes: {
    title: 'Title',
    slug: 'slug',
    teaser: null,
    author: {
      data: {
        id: 1,
        attributes: {
          name: 'Lukas Bals',
          locale: 'en',
          createdAt: '2022-01-10T15:36:45.012Z',
          updatedAt: '2022-01-10T15:36:45.042Z',
          img: {
            id: 72,
            alt: 'Lukas Bals',
            img: {
              data: {
                id: 10,
                attributes: {
                  name: 'Lukas_Bals.jpg',
                  alternativeText: '',
                  caption: '',
                  width: 1024,
                  height: 724,
                  formats: {
                    thumbnail: {
                      name: 'thumbnail_Lukas_Bals.jpg',
                      hash: 'thumbnail_Lukas_Bals_dc6741af55',
                      ext: '.jpg',
                      mime: 'image/jpeg',
                      width: 221,
                      height: 156,
                      size: 6.12,
                      path: null,
                      url: '/uploads/thumbnail_Lukas_Bals_dc6741af55.jpg',
                    },
                    large: {
                      name: 'large_Lukas_Bals.jpg',
                      hash: 'large_Lukas_Bals_dc6741af55',
                      ext: '.jpg',
                      mime: 'image/jpeg',
                      width: 1000,
                      height: 707,
                      size: 93,
                      path: null,
                      url: '/uploads/large_Lukas_Bals_dc6741af55.jpg',
                    },
                    medium: {
                      name: 'medium_Lukas_Bals.jpg',
                      hash: 'medium_Lukas_Bals_dc6741af55',
                      ext: '.jpg',
                      mime: 'image/jpeg',
                      width: 750,
                      height: 530,
                      size: 52.94,
                      path: null,
                      url: '/uploads/medium_Lukas_Bals_dc6741af55.jpg',
                    },
                    small: {
                      name: 'small_Lukas_Bals.jpg',
                      hash: 'small_Lukas_Bals_dc6741af55',
                      ext: '.jpg',
                      mime: 'image/jpeg',
                      width: 500,
                      height: 354,
                      size: 22.71,
                      path: null,
                      url: '/uploads/small_Lukas_Bals_dc6741af55.jpg',
                    },
                    xSmall: {
                      name: 'xSmall_Lukas_Bals.jpg',
                      hash: 'xSmall_Lukas_Bals_dc6741af55',
                      ext: '.jpg',
                      mime: 'image/jpeg',
                      width: 64,
                      height: 45,
                      size: 1.39,
                      path: null,
                      url: '/uploads/xSmall_Lukas_Bals_dc6741af55.jpg',
                    },
                  },
                  hash: 'Lukas_Bals_dc6741af55',
                  ext: '.jpg',
                  mime: 'image/jpeg',
                  size: 99.12,
                  url: '/uploads/Lukas_Bals_dc6741af55.jpg',
                  previewUrl: null,
                  provider: 'local',
                  provider_metadata: null,
                  createdAt: '2021-08-20T09:48:51.376Z',
                  updatedAt: '2021-08-20T09:48:51.389Z',
                },
              },
            },
          },
        },
      },
    },
    category: {
      data: {
        id: 1,
        attributes: {
          name: 'Business',
          locale: 'en',
          createdAt: '2022-01-10T14:59:44.830Z',
          updatedAt: '2022-01-10T14:59:44.839Z',
        },
      },
    },
    locale: 'en',
    createdAt: '2022-01-10T15:04:32.897Z',
    updatedAt: '2022-01-11T10:21:42.317Z',
    metadata: null,
    img: {
      id: 71,
      alt: 'Alt',
      img: {
        data: {
          id: 1,
          attributes: {
            name: 'default_shareimage.jpeg',
            alternativeText: '',
            caption: '',
            width: 1200,
            height: 630,
            formats: {
              thumbnail: {
                name: 'thumbnail_default_shareimage.jpeg',
                hash: 'thumbnail_default_shareimage_fecd5ccc7e',
                ext: '.jpeg',
                mime: 'image/jpeg',
                width: 245,
                height: 129,
                size: 9.36,
                path: null,
                url: '/uploads/thumbnail_default_shareimage_fecd5ccc7e.jpeg',
              },
              large: {
                name: 'large_default_shareimage.jpeg',
                hash: 'large_default_shareimage_fecd5ccc7e',
                ext: '.jpeg',
                mime: 'image/jpeg',
                width: 1000,
                height: 525,
                size: 132.73,
                path: null,
                url: '/uploads/large_default_shareimage_fecd5ccc7e.jpeg',
              },
              medium: {
                name: 'medium_default_shareimage.jpeg',
                hash: 'medium_default_shareimage_fecd5ccc7e',
                ext: '.jpeg',
                mime: 'image/jpeg',
                width: 750,
                height: 394,
                size: 78.75,
                path: null,
                url: '/uploads/medium_default_shareimage_fecd5ccc7e.jpeg',
              },
              small: {
                name: 'small_default_shareimage.jpeg',
                hash: 'small_default_shareimage_fecd5ccc7e',
                ext: '.jpeg',
                mime: 'image/jpeg',
                width: 500,
                height: 263,
                size: 35.08,
                path: null,
                url: '/uploads/small_default_shareimage_fecd5ccc7e.jpeg',
              },
              xSmall: {
                name: 'xSmall_default_shareimage.jpeg',
                hash: 'xSmall_default_shareimage_fecd5ccc7e',
                ext: '.jpeg',
                mime: 'image/jpeg',
                width: 64,
                height: 34,
                size: 1.31,
                path: null,
                url: '/uploads/xSmall_default_shareimage_fecd5ccc7e.jpeg',
              },
            },
            hash: 'default_shareimage_fecd5ccc7e',
            ext: '.jpeg',
            mime: 'image/jpeg',
            size: 188.72,
            url: '/uploads/default_shareimage_fecd5ccc7e.jpeg',
            previewUrl: null,
            provider: 'local',
            provider_metadata: null,
            createdAt: '2021-07-26T08:01:15.702Z',
            updatedAt: '2021-09-09T12:50:57.817Z',
          },
        },
      },
    },
    slices: [
      {
        __component: 'sections.rich-text',
        id: 6,
        content: '# This is my rich text!',
      },
    ],
    localizations: [
      {
        id: 2,
        locale: 'de',
      },
    ],
  },
};
