import IStrapiData from '@/models/strapi/IStrapiData';
import StrapiPage from '@/models/strapi/StrapiPage';

export const strapiPageMock: IStrapiData<StrapiPage> = {
  id: 7,
  attributes: {
    title: 'About us',
    slug: 'about',
    locale: 'en',
    publishedAt: '2021-08-21T07:27:03.352Z',
    createdAt: '2021-08-21T07:18:06.144Z',
    updatedAt: '2021-09-09T09:50:23.352Z',
    metadata: null,
    slices: [
      {
        __component: 'sections.full-width-image',
        id: 1,
        tagline: 'About tree.ly',
        title:
          'Our mission is to shape our future for the better by valuing its preservation',
        text: 'Climate change is the biggest challenge of our times. And it is happening now. The next few years are the most important ones and will have the most impact. ',
        image: {
          id: 20,
          alt: 'Image of trees',
          img: {
            id: 12,
            name: '000096530011.jpg',
            alternativeText: '',
            caption: '',
            width: 3130,
            height: 2075,
            formats: {
              thumbnail: {
                name: 'thumbnail_000096530011.jpg',
                hash: 'thumbnail_000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                width: 235,
                height: 156,
                size: 4.33,
                path: null,
                url: '/uploads/thumbnail_000096530011_0b109c6483.jpg',
              },
              xLarge: {
                name: 'xLarge_000096530011.jpg',
                hash: 'xLarge_000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                width: 1920,
                height: 1273,
                size: 557.3,
                path: null,
                url: '/uploads/xLarge_000096530011_0b109c6483.jpg',
              },
              large: {
                name: 'large_000096530011.jpg',
                hash: 'large_000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                width: 1000,
                height: 663,
                size: 90.8,
                path: null,
                url: '/uploads/large_000096530011_0b109c6483.jpg',
              },
              medium: {
                name: 'medium_000096530011.jpg',
                hash: 'medium_000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                width: 750,
                height: 497,
                size: 44.01,
                path: null,
                url: '/uploads/medium_000096530011_0b109c6483.jpg',
              },
              small: {
                name: 'small_000096530011.jpg',
                hash: 'small_000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                width: 500,
                height: 331,
                size: 17.19,
                path: null,
                url: '/uploads/small_000096530011_0b109c6483.jpg',
              },
              xSmall: {
                name: 'xSmall_000096530011.jpg',
                hash: 'xSmall_000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                width: 64,
                height: 42,
                size: 0.99,
                path: null,
                url: '/uploads/xSmall_000096530011_0b109c6483.jpg',
              },
            },
            hash: '000096530011_0b109c6483',
            ext: '.jpg',
            mime: 'image/jpeg',
            size: 1861.36,
            url: '/uploads/000096530011_0b109c6483.jpg',
            previewUrl: null,
            provider: 'local',
            provider_metadata: null,
            createdAt: '2021-08-21T07:26:43.056Z',
            updatedAt: '2021-08-21T07:26:43.066Z',
          },
        },
      },
      {
        __component: 'sections.text-with-text-cards',
        id: 1,
        tagline: 'Mission',
        title: 'We need a headline here',
        text: 'Our mission? To make the protection of our natural resources more valuable than its destruction. To shape our future for the better by valuing its preservation. Together. \n\nThat’s why our diverse team found a new technology venture that unlocks the carbon capture potential of our forests. How? By bringing together forest owners, carbon offsetters and public authorities. \n\nWith Tree.ly, Europe’s forests can easily participate in the new carbon market.',
        cards: [
          {
            id: 2,
            title: 'First Heading',
            text: 'Forest owners do something',
            icon: {
              id: 24,
              alt: 'Idea',
              img: {
                id: 14,
                name: 'lightBulb.svg',
                alternativeText: '',
                caption: '',
                width: 32,
                height: 32,
                formats: null,
                hash: 'light_Bulb_e2cc9d6c1a',
                ext: '.svg',
                mime: 'image/svg+xml',
                size: 2.87,
                url: '/uploads/light_Bulb_e2cc9d6c1a.svg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-23T08:15:29.794Z',
                updatedAt: '2021-08-23T08:15:29.808Z',
              },
            },
          },
          {
            id: 1,
            title: 'Another Heading',
            text: 'Carbon offsetters do that ... ',
            icon: {
              id: 23,
              alt: 'Coin',
              img: {
                id: 15,
                name: 'coin.svg',
                alternativeText: '',
                caption: '',
                width: 32,
                height: 32,
                formats: null,
                hash: 'coin_2a0aa3d446',
                ext: '.svg',
                mime: 'image/svg+xml',
                size: 1.66,
                url: '/uploads/coin_2a0aa3d446.svg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-23T08:16:02.429Z',
                updatedAt: '2021-08-23T08:16:02.439Z',
              },
            },
          },
        ],
        contact: null,
        shape: null,
      },
      {
        __component: 'sections.image-grid',
        id: 1,
        tagline: 'our team',
        title: 'The people behind Tree.ly',
        text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.',
        images: [
          {
            id: 3,
            title: 'Lukas Bals',
            subTitle: 'Engineeer',
            image: {
              id: 17,
              alt: 'Lukas Bals',
              img: {
                id: 10,
                name: 'Lukas_Bals.jpg',
                alternativeText: '',
                caption: '',
                width: 1024,
                height: 724,
                formats: {
                  thumbnail: {
                    name: 'thumbnail_Lukas_Bals.jpg',
                    hash: 'thumbnail_Lukas_Bals_dc6741af55',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 221,
                    height: 156,
                    size: 6.12,
                    path: null,
                    url: '/uploads/thumbnail_Lukas_Bals_dc6741af55.jpg',
                  },
                  large: {
                    name: 'large_Lukas_Bals.jpg',
                    hash: 'large_Lukas_Bals_dc6741af55',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 1000,
                    height: 707,
                    size: 93,
                    path: null,
                    url: '/uploads/large_Lukas_Bals_dc6741af55.jpg',
                  },
                  medium: {
                    name: 'medium_Lukas_Bals.jpg',
                    hash: 'medium_Lukas_Bals_dc6741af55',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 750,
                    height: 530,
                    size: 52.94,
                    path: null,
                    url: '/uploads/medium_Lukas_Bals_dc6741af55.jpg',
                  },
                  small: {
                    name: 'small_Lukas_Bals.jpg',
                    hash: 'small_Lukas_Bals_dc6741af55',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 500,
                    height: 354,
                    size: 22.71,
                    path: null,
                    url: '/uploads/small_Lukas_Bals_dc6741af55.jpg',
                  },
                  xSmall: {
                    name: 'xSmall_Lukas_Bals.jpg',
                    hash: 'xSmall_Lukas_Bals_dc6741af55',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 64,
                    height: 45,
                    size: 1.39,
                    path: null,
                    url: '/uploads/xSmall_Lukas_Bals_dc6741af55.jpg',
                  },
                },
                hash: 'Lukas_Bals_dc6741af55',
                ext: '.jpg',
                mime: 'image/jpeg',
                size: 99.12,
                url: '/uploads/Lukas_Bals_dc6741af55.jpg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-20T09:48:51.376Z',
                updatedAt: '2021-08-20T09:48:51.389Z',
              },
            },
          },
          {
            id: 4,
            title: 'Tobias Sutterlüty',
            subTitle: 'UI/UX',
            image: {
              id: 18,
              alt: 'Tobias Sutterlüty',
              img: {
                id: 12,
                name: '000096530011.jpg',
                alternativeText: '',
                caption: '',
                width: 3130,
                height: 2075,
                formats: {
                  thumbnail: {
                    name: 'thumbnail_000096530011.jpg',
                    hash: 'thumbnail_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 235,
                    height: 156,
                    size: 4.33,
                    path: null,
                    url: '/uploads/thumbnail_000096530011_0b109c6483.jpg',
                  },
                  xLarge: {
                    name: 'xLarge_000096530011.jpg',
                    hash: 'xLarge_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 1920,
                    height: 1273,
                    size: 557.3,
                    path: null,
                    url: '/uploads/xLarge_000096530011_0b109c6483.jpg',
                  },
                  large: {
                    name: 'large_000096530011.jpg',
                    hash: 'large_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 1000,
                    height: 663,
                    size: 90.8,
                    path: null,
                    url: '/uploads/large_000096530011_0b109c6483.jpg',
                  },
                  medium: {
                    name: 'medium_000096530011.jpg',
                    hash: 'medium_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 750,
                    height: 497,
                    size: 44.01,
                    path: null,
                    url: '/uploads/medium_000096530011_0b109c6483.jpg',
                  },
                  small: {
                    name: 'small_000096530011.jpg',
                    hash: 'small_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 500,
                    height: 331,
                    size: 17.19,
                    path: null,
                    url: '/uploads/small_000096530011_0b109c6483.jpg',
                  },
                  xSmall: {
                    name: 'xSmall_000096530011.jpg',
                    hash: 'xSmall_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 64,
                    height: 42,
                    size: 0.99,
                    path: null,
                    url: '/uploads/xSmall_000096530011_0b109c6483.jpg',
                  },
                },
                hash: '000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                size: 1861.36,
                url: '/uploads/000096530011_0b109c6483.jpg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-21T07:26:43.056Z',
                updatedAt: '2021-08-21T07:26:43.066Z',
              },
            },
          },
          {
            id: 5,
            title: 'Jodok Batlogg',
            subTitle: 'CTO',
            image: {
              id: 19,
              alt: 'Jodok Batlogg',
              img: {
                id: 13,
                name: 'Jodok-Batlogg.jpg',
                alternativeText: '',
                caption: '',
                width: 730,
                height: 411,
                formats: {
                  thumbnail: {
                    name: 'thumbnail_Jodok-Batlogg.jpg',
                    hash: 'thumbnail_Jodok_Batlogg_10c06b89ce',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 245,
                    height: 138,
                    size: 5.68,
                    path: null,
                    url: '/uploads/thumbnail_Jodok_Batlogg_10c06b89ce.jpg',
                  },
                  small: {
                    name: 'small_Jodok-Batlogg.jpg',
                    hash: 'small_Jodok_Batlogg_10c06b89ce',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 500,
                    height: 282,
                    size: 16.26,
                    path: null,
                    url: '/uploads/small_Jodok_Batlogg_10c06b89ce.jpg',
                  },
                  xSmall: {
                    name: 'xSmall_Jodok-Batlogg.jpg',
                    hash: 'xSmall_Jodok_Batlogg_10c06b89ce',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 64,
                    height: 36,
                    size: 1.18,
                    path: null,
                    url: '/uploads/xSmall_Jodok_Batlogg_10c06b89ce.jpg',
                  },
                },
                hash: 'Jodok_Batlogg_10c06b89ce',
                ext: '.jpg',
                mime: 'image/jpeg',
                size: 29.06,
                url: '/uploads/Jodok_Batlogg_10c06b89ce.jpg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-21T07:52:15.241Z',
                updatedAt: '2021-08-21T07:52:15.257Z',
              },
            },
          },
        ],
      },
      {
        __component: 'sections.text-card-grid',
        id: 1,
        tagline: 'Values are valueable',
        title: 'Our values in action',
        text: "In our dreams we run through lush meadows and forests. Everyday again, and in the evening come back home fulfilled. Together.\n\nThis is your unique opportunity to join the early founding team of tree.ly, led by seasoned entrepreneurs that build on a solid foundation and won't compromise on culture. \n\nThese are the things that set us apart from others. ",
        cards: [
          {
            id: 1,
            title: 'Title',
            text: 'They think this ... ',
            shape: {
              id: 27,
              alt: 'Shape',
              img: {
                id: 16,
                name: 'Shape Top Right.svg',
                alternativeText: '',
                caption: '',
                width: 196,
                height: 196,
                formats: null,
                hash: 'Shape_Top_Right_8a9fa01bb0',
                ext: '.svg',
                mime: 'image/svg+xml',
                size: 0.5,
                url: '/uploads/Shape_Top_Right_8a9fa01bb0.svg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-23T12:04:12.896Z',
                updatedAt: '2021-08-23T12:04:12.911Z',
              },
            },
          },
          {
            id: 2,
            title: 'Another one',
            text: 'They think this ... ',
            shape: {
              id: 25,
              alt: 'Telefonzelle',
              img: {
                id: 12,
                name: '000096530011.jpg',
                alternativeText: '',
                caption: '',
                width: 3130,
                height: 2075,
                formats: {
                  thumbnail: {
                    name: 'thumbnail_000096530011.jpg',
                    hash: 'thumbnail_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 235,
                    height: 156,
                    size: 4.33,
                    path: null,
                    url: '/uploads/thumbnail_000096530011_0b109c6483.jpg',
                  },
                  xLarge: {
                    name: 'xLarge_000096530011.jpg',
                    hash: 'xLarge_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 1920,
                    height: 1273,
                    size: 557.3,
                    path: null,
                    url: '/uploads/xLarge_000096530011_0b109c6483.jpg',
                  },
                  large: {
                    name: 'large_000096530011.jpg',
                    hash: 'large_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 1000,
                    height: 663,
                    size: 90.8,
                    path: null,
                    url: '/uploads/large_000096530011_0b109c6483.jpg',
                  },
                  medium: {
                    name: 'medium_000096530011.jpg',
                    hash: 'medium_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 750,
                    height: 497,
                    size: 44.01,
                    path: null,
                    url: '/uploads/medium_000096530011_0b109c6483.jpg',
                  },
                  small: {
                    name: 'small_000096530011.jpg',
                    hash: 'small_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 500,
                    height: 331,
                    size: 17.19,
                    path: null,
                    url: '/uploads/small_000096530011_0b109c6483.jpg',
                  },
                  xSmall: {
                    name: 'xSmall_000096530011.jpg',
                    hash: 'xSmall_000096530011_0b109c6483',
                    ext: '.jpg',
                    mime: 'image/jpeg',
                    width: 64,
                    height: 42,
                    size: 0.99,
                    path: null,
                    url: '/uploads/xSmall_000096530011_0b109c6483.jpg',
                  },
                },
                hash: '000096530011_0b109c6483',
                ext: '.jpg',
                mime: 'image/jpeg',
                size: 1861.36,
                url: '/uploads/000096530011_0b109c6483.jpg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-21T07:26:43.056Z',
                updatedAt: '2021-08-21T07:26:43.066Z',
              },
            },
          },
          {
            id: 3,
            title: 'Second Title',
            text: 'They think this ... ',
            shape: {
              id: 26,
              alt: 'Shape',
              img: {
                id: 17,
                name: 'Shape Gradient.svg',
                alternativeText: '',
                caption: '',
                width: 160,
                height: 160,
                formats: null,
                hash: 'Shape_Gradient_1c1b24c155',
                ext: '.svg',
                mime: 'image/svg+xml',
                size: 0.41,
                url: '/uploads/Shape_Gradient_1c1b24c155.svg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-23T12:21:34.061Z',
                updatedAt: '2021-08-23T12:21:34.073Z',
              },
            },
          },
          {
            id: 4,
            title: 'Hello',
            text: 'World',
            shape: {
              id: 28,
              alt: 'Alt text',
              img: {
                id: 11,
                name: 'shape.svg',
                alternativeText: '',
                caption: '',
                width: 440,
                height: 440,
                formats: null,
                hash: 'shape_96c76f75ab',
                ext: '.svg',
                mime: 'image/svg+xml',
                size: 0.47,
                url: '/uploads/shape_96c76f75ab.svg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-20T14:03:48.689Z',
                updatedAt: '2021-08-20T14:03:48.709Z',
              },
            },
          },
          {
            id: 5,
            title: 'Heading',
            text: 'Hello',
            shape: {
              id: 29,
              alt: 'Asdf',
              img: {
                id: 17,
                name: 'Shape Gradient.svg',
                alternativeText: '',
                caption: '',
                width: 160,
                height: 160,
                formats: null,
                hash: 'Shape_Gradient_1c1b24c155',
                ext: '.svg',
                mime: 'image/svg+xml',
                size: 0.41,
                url: '/uploads/Shape_Gradient_1c1b24c155.svg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-23T12:21:34.061Z',
                updatedAt: '2021-08-23T12:21:34.073Z',
              },
            },
          },
          {
            id: 6,
            title: 'Headline',
            text: 'Sewas',
            shape: {
              id: 30,
              alt: 'Grüazi',
              img: {
                id: 17,
                name: 'Shape Gradient.svg',
                alternativeText: '',
                caption: '',
                width: 160,
                height: 160,
                formats: null,
                hash: 'Shape_Gradient_1c1b24c155',
                ext: '.svg',
                mime: 'image/svg+xml',
                size: 0.41,
                url: '/uploads/Shape_Gradient_1c1b24c155.svg',
                previewUrl: null,
                provider: 'local',
                provider_metadata: null,
                createdAt: '2021-08-23T12:21:34.061Z',
                updatedAt: '2021-08-23T12:21:34.073Z',
              },
            },
          },
        ],
      },
    ],
    localizations: [
      {
        id: 10,
        locale: 'de',
        publishedAt: '2021-09-09T10:14:28.802Z',
      },
    ],
  },
};
